# Generated by Django 2.1.7 on 2019-08-31 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='yox',
        ),
        migrations.AddField(
            model_name='books',
            name='for_rent',
            field=models.CharField(choices=[(
                'Var', 'var'), ('Yoxdur', 'yoxdur')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
