# Generated by Django 2.1.7 on 2019-08-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190901_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Ad',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='books',
            name='Mezmun',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='books',
            name='Qiymet',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='books',
            name='Yazichi',
            field=models.CharField(default='', max_length=25),
        ),
    ]
