# Generated by Django 2.1.7 on 2019-08-31 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190901_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='for_rent',
            new_name='Icare_ucun',
        ),
    ]
