# Generated by Django 2.1.7 on 2019-08-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190901_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Ad',
            field=models.CharField(default='', max_length=70),
        ),
    ]
