# Generated by Django 2.1.7 on 2019-09-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190901_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Ad',
            field=models.CharField(
                default='', max_length=70, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='books',
            name='Icare_ucun',
            field=models.CharField(choices=[('Mövcud', 'mövcud'), (
                'Mövcud deyil', 'övcud deyil')], max_length=10, verbose_name='Kirayə üçün mövcudluğu'),
        ),
        migrations.AlterField(
            model_name='books',
            name='Mezmun',
            field=models.TextField(default='', verbose_name='Məzmunu'),
        ),
        migrations.AlterField(
            model_name='books',
            name='Qiymet',
            field=models.CharField(
                default='', max_length=8, verbose_name='Qiymət'),
        ),
        migrations.AlterField(
            model_name='books',
            name='Yazichi',
            field=models.CharField(
                default='', max_length=25, verbose_name='Yazar'),
        ),
    ]
