# Generated by Django 2.1.7 on 2019-09-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190901_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Icare_ucun',
            field=models.CharField(choices=[('Mövcud', 'mövcud'), (
                'Mövcud deyil', 'mövcud deyil')], max_length=10, verbose_name='Kirayə üçün mövcudluğu'),
        ),
        migrations.AlterField(
            model_name='books',
            name='Mezmun',
            field=models.TextField(default='', verbose_name='Məzmun'),
        ),
    ]
