# Generated by Django 2.1.7 on 2019-09-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190901_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Kitablar',
        ),
    ]
