# Generated by Django 2.1.7 on 2019-09-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20190903_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitablar',
            name='janr',
            field=models.CharField(choices=[('Dedektiv', 'dedektiv'), ('Fantastik', 'fantastik'), ('Psixoloji', 'psixoloji'), ('Hüquq', 'hüquq'), (
                'Roman', 'roman'), ('Dünya Ədəbiyyatı', 'dünya ədəbiyyatı'), ('Fəlsəfə', 'fəlsəfə')], default='', max_length=100, verbose_name='Janr'),
        ),
    ]
