# Generated by Django 2.1.7 on 2019-09-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20190904_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitablar',
            name='janr',
            field=models.CharField(choices=[('Dedektiv', 'dedektiv'), ('Fantastik', 'fantastik'), ('Psixoloji', 'psixoloji'), ('Hüquq', 'hüquq'), (
                'Roman', 'roman'), ('Dünya Ədəbiyyatı', 'dünya ədəbiyyatı'), ('Fəlsəfə', 'felsefe')], default='', max_length=100, verbose_name='Janr'),
        ),
    ]
