# Generated by Django 2.1.7 on 2019-09-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20190909_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitablar',
            name='Ad',
            field=models.CharField(max_length=70, verbose_name='Ad'),
        ),
    ]
