# Generated by Django 2.2.8 on 2020-04-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20191120_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitablar',
            name='janr',
            field=models.CharField(choices=[('Dedektiv', 'dedektiv'), ('Fantastik', 'fantastik'), ('Psixoloji', 'psixoloji'), ('Hüquq', 'hüquq'), (
                'Roman', 'roman'), ('Dünya Ədəbiyyatı', 'dünya ədəbiyyatı'), ('Fəlsəfə', 'fəlsəfə')], max_length=100, verbose_name='Janr'),
        ),
    ]
