# Generated by Django 2.2.8 on 2020-04-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20200415_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitablar',
            name='janr',
            field=models.CharField(choices=[('dedektiv', 'Dedektiv'), ('fantastik', 'Fantastik'), ('psixoloji', 'Psixoloji'), ('huquq', 'Hüquq'), (
                'roman', 'Roman'), ('dunya_edebiyyati', 'Dünya ədəbiyyatı'), ('felsefe', 'Fəlsəfə')], max_length=100, verbose_name='Janr'),
        ),
    ]
