# Generated by Django 2.2.8 on 2020-04-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_auto_20200419_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitablar',
            name='janr',
            field=models.CharField(choices=[('dedektiv', 'Dedektiv'), ('fantastik', 'Fantastik'), ('psixoloji', 'psixoloji'), (
                'huquq', 'Hüquq'), ('roman', 'roman'), ('dunya_edebiyyati', 'Dünya ədəbiyyatı'), ('felsefe', 'Fəlsəfə')], max_length=100),
        ),
    ]
