# Generated by Django 2.2.8 on 2020-04-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20200419_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitablar',
            name='janr',
            field=models.CharField(choices=[('dedektiv', 'Dedektiv'), ('fantastik', 'Fantastik'), ('psixoloji', 'Psixoloji'), (
                'huquq', 'Hüquq'), ('roman', 'Roman'), ('dunya_edebiyyati', 'Dünya ədəbiyyatı'), ('felsefe', 'Fəlsəfə')], max_length=20),
        ),
    ]
