# Generated by Django 2.2.8 on 2020-06-25 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0028_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitablar',
            name='favourite',
            field=models.ManyToManyField(
                blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='favorites',
        ),
    ]
