# Generated by Django 2.2.8 on 2020-08-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_auto_20200626_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitablar',
            options={'ordering': ['tarix'], 'verbose_name_plural': 'Kitablar'},
        ),
    ]
